### ISSUE TITLE
FR: Provider should be aware of max string size constraints

### ISSUE THREAD

**Issue by amy-hashi** [hashicorp/terraform-provider-random#127] opened 2020-10-28 14:41 UTC
The max string size appears to be 4kb, but the random provider appears to allow an unlimited size to be passed. The first plan/apply will appear to complete and create a state file, but that state file can then never be properly read from when it contains a string larger than 4kb.

### Terraform Version
v0.12.29

### Affected Resource(s)
Please list the resources as a list, for example:
- random_*

### Terraform Configuration Files
Terraform code:
```hcl
resource "random_id" "id" {
	byte_length = var.length

	keepers = {
    uuid = uuid()
  }
}
```
Where length equals anything over 4k

### Debug Output
A second plan against that same configuration will throw this error: 

`Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8817003 vs. 4194304)`

### Expected Behavior
As there is a known limit, the provider should have a maximum length in place to prevent end users from accidentally creating an unusable statefile. 

### Actual Behavior
Terraform allows a string to be created beyond the size it can read in later. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` using the above code where the output is over 4k
2. Run `terraform plan`

**Comment by bendbennett** [comment] 2022-05-17 08:49
Closing as I can't reproduce. @amy-hashi please open another issue providing as much detail as possible if you are still seeing this problem.

**Closed by bendbennett** 2022-05-17 08:49 UTC
Labels: enhancement
