### ISSUE TITLE
Random_string Override special Issue 

### ISSUE THREAD

**Issue by rishabhjain1510** [hashicorp/terraform-provider-random#325] opened 2022-09-21 10:46 UTC
### Terraform CLI and Provider Versions

Terraform Version : - v0.13.6
Provider version :- 3.75.1
Random Provider version:-  v3.4.3

### Terraform Configuration

provider "aws" {
  version = "~> 3.75.1"
  region = var.region
  assume_role {
    role_arn     = var.role_arn
    session_name = "Opticloud_Provisioner"
    external_id  = "Opticloud"
  }
}

```terraform
resource "random_string" "password" {
  length           = 12
  min_lower        = 1
  min_numeric      = 1
  min_upper        = 1
  min_special      = 1
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}
```

### Expected Behavior

It should create a password , with all the properties specified .

### Actual Behavior

terraform plan throws an error .

Provider "registry.terraform.io/hashicorp/random" planned an invalid value for
module.aurora-pp-26cmbjo6oyplk.random_string.password.override_special:
planned value cty.NullVal(cty.String) does not match config value
cty.StringVal("!#$%&*()-_=+[]{}<>:?").

### Steps to Reproduce

1. `terraform plan`

### How much impact is this issue causing?

High

### Logs

https://gist.github.com/rishabhjain1510/65c279d1d2c0149208e109b66fcce29f

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment] 2022-09-21 11:28
Hi @rishabhjain1510 :wave:
Thanks for raising this issue and apologies for any inconvenience.

Would it be possible for you to show the (redacted if necessary) current state of that particular resource? e.g.

```console
$ terraform state show random_string_password
```

Thanks

**Comment by rishabhjain1510** [comment] 2022-09-21 11:50
Hi @bendbennett , 

Here is the state.

# module.rds-instance-pp-3hdhqno7z4jzo.random_string.password:
resource "random_string" "password" {
    id          = "LPAzL9WBiOVG"
    length      = 12
    lower       = true
    min_lower   = 1
    min_numeric = 1
    min_special = 0
    min_upper   = 1
    number      = true
    result      = "LPAzL9WBiOVG"
    special     = false
    upper       = true
}

**Comment by bendbennett** [comment] 2022-09-21 12:53
@rishabhjain1510 looking at your output from `terraform state show random_string.password`, the absence of the `numeric` attribute suggests that you were using `v3.2.0` or earlier version of the provider as `numeric` was introduced in [v3.3.0](https://github.com/hashicorp/terraform-provider-random/releases/tag/v3.3.0). 

The state also indicates that the configuration for `random_string` was previously something like:
```terraform
resource "random_string" "password" {
  length      = 12
  min_lower   = 1
  min_numeric = 1
  min_special = 0
  min_upper   = 1
  special     = false
}
```

I tried to reproduce the issue you describe by using `v3.2.0` of the provider, which gives me a very similar state to that which you described:
```console
terraform state show random_string.password
# random_string.password:
resource "random_string" "password" {
    id          = "tcHyjh5Fuzqi"
    length      = 12
    lower       = true
    min_lower   = 1
    min_numeric = 1
    min_special = 0
    min_upper   = 1
    number      = true
    result      = "tcHyjh5Fuzqi"
    special     = false
    upper       = true
}
```

I then updated to `v3.4.3` and modified the configuration to the following:
```terraform
resource "random_string" "password" {
  length           = 12
  min_lower        = 1
  min_numeric      = 1
  min_upper        = 1
  min_special      = 1
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}
```

Running `terraform plan` then produced the following output:
```console
Terraform will perform the following actions:

  # random_string.password must be replaced
-/+ resource "random_string" "password" {
      ~ id               = "tcHyjh5Fuzqi" -> (known after apply)
      ~ min_special      = 0 -> 1 # forces replacement
      + override_special = "!#$%&*()-_=+[]{}<>:?" # forces replacement
      ~ result           = "tcHyjh5Fuzqi" -> (known after apply)
      ~ special          = false -> true # forces replacement
        # (8 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

I was unable to reproduce the issue you describe where `terraform plan` produces an error.

**Comment by bendbennett** [comment] 2022-09-22 13:31
Hi @rishabhjain1510,

If I run through the process I described in https://github.com/hashicorp/terraform-provider-random/issues/325#issuecomment-1253669306 and then update the configuration as you describe prior to running `terraform plan` with `v3.4.3` I see the following:
```terraform
resource "random_string" "password" {
  length           = 12
  min_lower        = 1
  min_numeric      = 1
  min_upper        = 1
  min_special      = 1
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"

  lifecycle {
    ignore_changes = all
  }
}
```

```console
random_string.password: Refreshing state... [id=tcHyjh5Fuzqi]

No changes. Your infrastructure matches the configuration.
```

**Comment by bendbennett** [comment] 2022-11-30 11:13
@rishabhjain1510 I'm going to close this issue as I'm unable to reproduce the issue you describe and there's been no further feedback. If you are still experiencing problems please file another issue and if possible supply the necessary configuration to reproduce the issue. Thanks.

**Closed by bendbennett** 2022-11-30 11:13 UTC
Labels: bug
